import type {
  Player,
  RoomListItem,
  MatchData,
  LeaderboardEntry,
  RecentMatch,
} from "@/types";

export const MOCK_CURRENT_PLAYER: Player = {
  id: "player-self",
  name: "辯論王者",
  debateRank: "gold",
  banterRank: "platinum",
  debateMMR: 1234,
  banterMMR: 1567,
  wins: 42,
  losses: 18,
};

export const MOCK_DEBATE_ROOMS: RoomListItem[] = [
  {
    id: "room-1",
    topic: "人工智慧是否應該取代法官？",
    mode: "1v1",
    type: "debate",
    currentPlayers: 1,
    maxPlayers: 2,
    status: "waiting",
    isRanked: false,
  },
  {
    id: "room-2",
    topic: "強制服兵役是否有助於國家安全？",
    mode: "3v3",
    type: "debate",
    currentPlayers: 5,
    maxPlayers: 6,
    status: "waiting",
    isRanked: true,
  },
  {
    id: "room-3",
    topic: "社群媒體是否有益於青少年心理健康？",
    mode: "1v1",
    type: "debate",
    currentPlayers: 2,
    maxPlayers: 2,
    status: "in_progress",
    isRanked: false,
  },
];

export const MOCK_BANTER_ROOMS: RoomListItem[] = [
  {
    id: "room-4",
    topic: "貓咪 vs 狗狗，誰才是最佳寵物？",
    mode: "1v1",
    type: "banter",
    currentPlayers: 0,
    maxPlayers: 2,
    status: "waiting",
    isRanked: false,
  },
  {
    id: "room-5",
    topic: "鳳梨到底能不能加在披薩上？",
    mode: "3v3",
    type: "banter",
    currentPlayers: 3,
    maxPlayers: 6,
    status: "waiting",
    isRanked: false,
  },
  {
    id: "room-6",
    topic: "早起的鳥兒真的有蟲吃嗎？",
    mode: "1v1",
    type: "banter",
    currentPlayers: 1,
    maxPlayers: 2,
    status: "waiting",
    isRanked: false,
  },
];

export const MOCK_MATCH: MatchData = {
  id: "match-1",
  topic: "人工智慧是否應該取代人類法官？",
  mode: "1v1",
  type: "debate",
  isRanked: true,
  currentRound: 2,
  totalRounds: 4,
  status: "in_progress",
  proTeam: [
    {
      id: "p1",
      name: "科技先鋒",
      debateRank: "gold",
      banterRank: "silver",
      debateMMR: 1100,
      banterMMR: 800,
      wins: 30,
      losses: 12,
    },
  ],
  conTeam: [
    {
      id: "p2",
      name: "人道衛士",
      debateRank: "platinum",
      banterRank: "gold",
      debateMMR: 1600,
      banterMMR: 1050,
      wins: 55,
      losses: 20,
    },
  ],
  messages: [
    {
      id: "msg-1",
      playerId: "p1",
      playerName: "科技先鋒",
      side: "pro",
      content:
        "AI 的邏輯判斷能力遠超人類，不受情緒干擾，可以做出更公正、更一致的判決。",
      timestamp: "2024-01-15T10:00:00Z",
      round: 1,
    },
    {
      id: "msg-2",
      playerId: "p2",
      playerName: "人道衛士",
      side: "con",
      content:
        "法律判決需要對人性的理解與同情心，AI 缺乏這種能力，可能造成機械式的不公義。",
      timestamp: "2024-01-15T10:02:00Z",
      round: 1,
    },
    {
      id: "msg-3",
      playerId: "p1",
      playerName: "科技先鋒",
      side: "pro",
      content:
        "研究顯示人類法官的判決受到午餐時間、心情等因素影響，AI 可以消除這些偏誤。",
      timestamp: "2024-01-15T10:05:00Z",
      round: 2,
    },
    {
      id: "msg-4",
      playerId: "p2",
      playerName: "人道衛士",
      side: "con",
      content:
        "AI 的訓練資料本身存在偏誤，這些偏誤會被系統性地放大，影響更多弱勢族群。",
      timestamp: "2024-01-15T10:07:00Z",
      round: 2,
    },
  ],
  scores: {
    pro: { logic: 7, expression: 8, counterArgument: 6, total: 21 },
    con: { logic: 9, expression: 7, counterArgument: 8, total: 24 },
  },
  aiJudgeComment:
    "目前反方在邏輯架構上較為嚴謹，成功指出 AI 偏誤的核心問題。正方需要提供更具體的研究案例支撐主張。第 3 回合反駁將是關鍵轉折點。",
};

export const MOCK_LEADERBOARD_DEBATE: LeaderboardEntry[] = [
  {
    rank: 1,
    player: {
      id: "l1",
      name: "辯論之神",
      debateRank: "grandmaster",
      banterRank: "master",
      debateMMR: 3250,
      banterMMR: 2600,
      wins: 120,
      losses: 15,
    },
    mmr: 3250,
    wins: 120,
    losses: 15,
    winRate: 89,
    mode: "debate",
  },
  {
    rank: 2,
    player: {
      id: "l2",
      name: "邏輯大師",
      debateRank: "master",
      banterRank: "diamond",
      debateMMR: 2890,
      banterMMR: 2100,
      wins: 98,
      losses: 22,
    },
    mmr: 2890,
    wins: 98,
    losses: 22,
    winRate: 82,
    mode: "debate",
  },
  {
    rank: 3,
    player: {
      id: "l3",
      name: "犀利反駁",
      debateRank: "master",
      banterRank: "gold",
      debateMMR: 2700,
      banterMMR: 1100,
      wins: 85,
      losses: 20,
    },
    mmr: 2700,
    wins: 85,
    losses: 20,
    winRate: 81,
    mode: "debate",
  },
  {
    rank: 4,
    player: {
      id: "l4",
      name: "理性分析",
      debateRank: "diamond",
      banterRank: "platinum",
      debateMMR: 2450,
      banterMMR: 1800,
      wins: 72,
      losses: 25,
    },
    mmr: 2450,
    wins: 72,
    losses: 25,
    winRate: 74,
    mode: "debate",
  },
  {
    rank: 5,
    player: {
      id: "l5",
      name: "快速立論",
      debateRank: "diamond",
      banterRank: "silver",
      debateMMR: 2200,
      banterMMR: 700,
      wins: 61,
      losses: 28,
    },
    mmr: 2200,
    wins: 61,
    losses: 28,
    winRate: 69,
    mode: "debate",
  },
  {
    rank: 6,
    player: MOCK_CURRENT_PLAYER,
    mmr: 1234,
    wins: 42,
    losses: 18,
    winRate: 70,
    mode: "debate",
  },
];

export const MOCK_LEADERBOARD_BANTER: LeaderboardEntry[] = [
  {
    rank: 1,
    player: {
      id: "b1",
      name: "嘴砲王",
      debateRank: "silver",
      banterRank: "grandmaster",
      debateMMR: 600,
      banterMMR: 3100,
      wins: 200,
      losses: 30,
    },
    mmr: 3100,
    wins: 200,
    losses: 30,
    winRate: 87,
    mode: "banter",
  },
  {
    rank: 2,
    player: {
      id: "b2",
      name: "幽默大師",
      debateRank: "bronze",
      banterRank: "master",
      debateMMR: 200,
      banterMMR: 2750,
      wins: 150,
      losses: 40,
    },
    mmr: 2750,
    wins: 150,
    losses: 40,
    winRate: 79,
    mode: "banter",
  },
  {
    rank: 3,
    player: {
      id: "b3",
      name: "閃電反擊",
      debateRank: "gold",
      banterRank: "master",
      debateMMR: 1050,
      banterMMR: 2600,
      wins: 130,
      losses: 45,
    },
    mmr: 2600,
    wins: 130,
    losses: 45,
    winRate: 74,
    mode: "banter",
  },
  {
    rank: 4,
    player: MOCK_CURRENT_PLAYER,
    mmr: 1567,
    wins: 42,
    losses: 18,
    winRate: 70,
    mode: "banter",
  },
  {
    rank: 5,
    player: {
      id: "b4",
      name: "毒舌評論",
      debateRank: "platinum",
      banterRank: "gold",
      debateMMR: 1800,
      banterMMR: 1200,
      wins: 88,
      losses: 40,
    },
    mmr: 1200,
    wins: 88,
    losses: 40,
    winRate: 69,
    mode: "banter",
  },
];

export const MOCK_RECENT_MATCHES: RecentMatch[] = [
  {
    id: "m1",
    topic: "AI 應該有投票權嗎？",
    mode: "1v1",
    type: "debate",
    result: "win",
    date: "2024-01-15T10:00:00Z",
    opponent: "科技懷疑者",
  },
  {
    id: "m2",
    topic: "鳳梨可以加在披薩上嗎？",
    mode: "1v1",
    type: "banter",
    result: "win",
    date: "2024-01-14T15:30:00Z",
    opponent: "義大利衛道士",
  },
  {
    id: "m3",
    topic: "強制服兵役是否必要？",
    mode: "3v3",
    type: "debate",
    result: "loss",
    date: "2024-01-14T09:00:00Z",
    opponent: "愛國先鋒隊",
  },
  {
    id: "m4",
    topic: "早睡早起是否適合現代人？",
    mode: "1v1",
    type: "banter",
    result: "win",
    date: "2024-01-13T20:00:00Z",
    opponent: "夜貓子聯盟",
  },
  {
    id: "m5",
    topic: "死刑應該廢除嗎？",
    mode: "1v1",
    type: "debate",
    result: "loss",
    date: "2024-01-12T14:00:00Z",
    opponent: "正義守護者",
  },
];
